version: '3.8'

services:
  frontend:
    build:
      context: ./frontend      # Path to the directory containing the React Dockerfile
      dockerfile: Dockerfile    # Name of the React Dockerfile
    ports:
      - "3000:3000"             # Map port 3000 on localhost to port 3000 in the container
    networks:
      - app_network

  backend:
    build:
      context: ./backend        # Path to the directory containing the PHP Dockerfile
      dockerfile: Dockerfile    # Name of the PHP Dockerfile
    ports:
      - "80:80"                 # Map port 80 on localhost to port 80 in the container
    networks:
      - app_network

networks:
  app_network:
    driver: bridge